project:
  type: website
  output-dir: docs

website:
  title: "Melissa May"
  navbar:
    background: "#2C5F2D"
    foreground: white
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
  page-footer:
    background: light
    left: Created and maintained by Melissa May.
    right: Built with GitHub pages and Quarto.

format:
  html:
    theme: United
    toc: true
    page-layout: full

editor: visual

